### ISSUE TITLE
Webpack 5 Warning

### ISSUE THREAD

**Issue by tm1000** [MQuy/webpack-deadcode-plugin#35]
Warning from Webpack 5: `(node:71) [DEP_WEBPACK_CHUNK_MODULES_ITERABLE] DeprecationWarning: Chunk.modulesIterable: Use new ChunkGraph API`

Ref: https://github.com/MQuy/webpack-deadcode-plugin/blob/71128366cb8ea2237ef10863274d72d3eb792c2c/src/detect.js#L49

**Comment by Slapbox** [comment]
Anyone know how to update the code to fix this?

**Comment by Slapbox** [comment]
It looks like the code is already trying to check for whether it's running in Webpack 5 or not. I'm guessing `isWebpack5` isn't evaluating to `true` when it should.

Some context on what working code might look like: https://stackoverflow.com/a/64809829

**Comment by MQuy** [comment]
hi @tm1000 and @Slapbox, thanks for your report. I released 0.1.15 and it should fix that warning issue

**Comment by Slapbox** [comment]
Looks good!
