### ISSUE TITLE
Readme is not working

### ISSUE THREAD

**Issue by longkt90** [MQuy/webpack-deadcode-plugin#4]
<img width="814" alt="screen shot 2018-04-10 at 3 21 11 pm" src="https://user-images.githubusercontent.com/3582650/38541858-e27349c6-3cd2-11e8-9938-c99d82b9fc27.png">

**Comment by MQuy** [comment]
it seems the github's problem. If you refresh readme again, it will be ok?

**Comment by longkt90** [comment]
It's still having errors, I refreshed a few thousand times already :omg:

**Comment by MQuy** [comment]
seems like it happens on every readme which uses `http://shields.io/`, will find an alternative service 👍🏻
